name 'biemond-jdk7'
version '0.1.0'
author 'Edwin Biemond'
source 'https://github.com/biemond/puppet/tree/master/modules/jdk7'
description "Oracle JDK7 puppet module"
project_page 'http://technology.amis.nl/2012/10/13/configure-fmw-servers-with-puppet/'
license 'GNU General Public License version 3 of the License'
