name 'biemond-orautils'
version '0.2.1'

author 'Edwin Biemond'
license 'Apache 2.0'
project_page 'https://github.com/biemond/puppet/tree/master/modules/orautils'
source 'https://github.com/biemond/puppet/tree/master/modules/oradb'
summary 'Oracle WebLogic and Database linux utilities scripts'
description 'Oracle WebLogic and Database linux utilities scripts'
