name 'biemond-wls'
version '0.3.0'
author 'Edwin Biemond'
source 'https://github.com/biemond/puppet/tree/master/modules/wls'
description "Oracle WebLogic / Fusion Middleware puppet module"
project_page 'http://technology.amis.nl/2012/10/13/configure-fmw-servers-with-puppet/'
license 'GNU General Public License version 3 of the License'

dependency 'puppetlabs/registry', '>= 0.1.1'
