name 'biemond-wls'
version '1.2.9'

author 'Edwin Biemond'
license 'Apache 2.0'
project_page 'http://technology.amis.nl/2012/10/13/configure-fmw-servers-with-puppet/'
source 'https://github.com/biemond/puppet/tree/master/modules/wls'
summary 'Oracle WebLogic / Fusion Middleware ( ADF, OSB, WebCenter, SOA Suite, WebCenter ) puppet module'
description 'Oracle WebLogic / Fusion Middleware puppet module'
dependency 'puppetlabs/registry', '>=0.1.1'
